CREATE TABLE [dbo].[MovieResult] (
    [ItemId]            INT            NOT NULL,
    [ItemSearchTitle]   NVARCHAR (100) NOT NULL,
    [ItemSource]        INT            NOT NULL,
    [RowId]             INT            IDENTITY (1, 1) NOT NULL,
    [ItemSearchYear]    INT            NULL,
    [ApiUrl]            VARCHAR (200)  NULL,
    [ResultTitle]       NVARCHAR (100) NULL,
    [ResultYear]        INT            NULL,
    [IsMovie]           BIT            CONSTRAINT [df_MovieResult_IsMovie_1] DEFAULT ((1)) NULL,
    [ResultCt]          INT            NULL,
    [Page]              INT            NULL,
    [Total_Pages]       INT            NULL,
    [Total_Results]     INT            NULL,
    [ResultNum]         INT            CONSTRAINT [df_MovieResult_ResultNum_1] DEFAULT ((0)) NULL,
    [Genre_Ids]         VARCHAR (100)  NULL,
    [Original_Language] VARCHAR (50)   NULL,
    [Original_Title]    NVARCHAR (100) NULL,
    [Overview]          NVARCHAR (MAX) NULL,
    [Release_Date]      VARCHAR (50)   NULL,
    [Poster_Path]       VARCHAR (250)  NULL,
    [Popularity]        FLOAT (53)     NULL,
    [Video]             BIT            NULL,
    [Vote_Average]      FLOAT (53)     NULL,
    [Vote_Count]        INT            NULL,
    [Rated]             VARCHAR (50)   NULL,
    [Released]          VARCHAR (50)   NULL,
    [Runtime]           VARCHAR (50)   NULL,
    [Genre]             VARCHAR (50)   NULL,
    [Director]          NVARCHAR (100) NULL,
    [Writer]            NVARCHAR (100) NULL,
    [Actors]            NVARCHAR (MAX) NULL,
    [Plot]              NVARCHAR (MAX) NULL,
    [Language]          NVARCHAR (50)  NULL,
    [Country]           NVARCHAR (50)  NULL,
    [Awards]            NVARCHAR (100) NULL,
    [Poster]            VARCHAR (200)  NULL,
    [MetaScore]         VARCHAR (50)   NULL,
    [ImdbRating]        VARCHAR (50)   NULL,
    [ImdbVotes]         VARCHAR (50)   NULL,
    [ImdbId]            VARCHAR (50)   NULL,
    [Type]              NVARCHAR (100) NULL,
    [TMeter]            VARCHAR (100)  NULL,
    [TImage]            VARCHAR (200)  NULL,
    [TRating]           VARCHAR (50)   NULL,
    [TReviews]          NVARCHAR (MAX) NULL,
    [TFresh]            VARCHAR (50)   NULL,
    [TRotten]           VARCHAR (50)   NULL,
    [TConsensus]        VARCHAR (50)   NULL,
    [TUserMeter]        VARCHAR (50)   NULL,
    [TUserRating]       VARCHAR (50)   NULL,
    [TUserReviews]      NVARCHAR (MAX) NULL,
    [DVD]               NVARCHAR (100) NULL,
    [BoxOffice]         NVARCHAR (50)  NULL,
    [Production]        NVARCHAR (50)  NULL,
    [Website]           NVARCHAR (200) NULL,
    [Response]          VARCHAR (10)   NULL,
    [AddedOn]           DATETIME       CONSTRAINT [df_MovieResult_AddedOn_1] DEFAULT (getutcdate()) NULL,
    [ChangedOn]         DATETIME       CONSTRAINT [df_MovieResult_ChangedOn_1] DEFAULT (getutcdate()) NULL,
    CONSTRAINT [PK_MovieResult_1] PRIMARY KEY CLUSTERED ([ItemId] ASC, [ItemSource] ASC, [RowId] ASC)
);

