//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace SqlExpressNovember.EntityClasses
{
	/// <summary>Class which represents the entity 'ApiDataSource'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class ApiDataSource : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="ApiDataSource"/> class.</summary>
		public ApiDataSource() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the Id field. </summary>
		[DataMember]
		public System.Int32 Id { get; set;}
		/// <summary>Gets or sets the SourceBaseUrl field. </summary>
		[DataMember]
		public System.String SourceBaseUrl { get; set;}
		/// <summary>Gets or sets the SourceName field. </summary>
		[DataMember]
		public System.String SourceName { get; set;}
		#endregion
	}
}
