//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace SqlExpressNovember.EntityClasses
{
	/// <summary>Class which represents the entity 'MovieNotFound'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class MovieNotFound : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="MovieNotFound"/> class.</summary>
		public MovieNotFound() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the AddedOn field. </summary>
		[DataMember]
		public Nullable<System.DateTime> AddedOn { get; set;}
		/// <summary>Gets or sets the ChangedOn field. </summary>
		[DataMember]
		public Nullable<System.DateTime> ChangedOn { get; set;}
		/// <summary>Gets or sets the ItemId field. </summary>
		[DataMember]
		public System.Int32 ItemId { get; set;}
		/// <summary>Gets or sets the ItemSearchTitle field. </summary>
		[DataMember]
		public System.String ItemSearchTitle { get; set;}
		/// <summary>Gets or sets the ItemSearchYear field. </summary>
		[DataMember]
		public Nullable<System.Int32> ItemSearchYear { get; set;}
		/// <summary>Gets or sets the ItemSource field. </summary>
		[DataMember]
		public System.Int32 ItemSource { get; set;}
		/// <summary>Gets or sets the RowId field. </summary>
		[DataMember]
		public System.Int32 RowId { get; set;}
		#endregion
	}
}
