//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace SqlExpressNovember.EntityClasses
{
	/// <summary>Class which represents the entity 'MovieCreditResult'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class MovieCreditResult : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="MovieCreditResult"/> class.</summary>
		public MovieCreditResult() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the AddedOn field. </summary>
		[DataMember]
		public Nullable<System.DateTime> AddedOn { get; set;}
		/// <summary>Gets or sets the ApiUrl field. </summary>
		[DataMember]
		public System.String ApiUrl { get; set;}
		/// <summary>Gets or sets the CastId field. </summary>
		[DataMember]
		public Nullable<System.Int32> CastId { get; set;}
		/// <summary>Gets or sets the ChangedOn field. </summary>
		[DataMember]
		public Nullable<System.DateTime> ChangedOn { get; set;}
		/// <summary>Gets or sets the Character field. </summary>
		[DataMember]
		public System.String Character { get; set;}
		/// <summary>Gets or sets the CreditId field. </summary>
		[DataMember]
		public System.String CreditId { get; set;}
		/// <summary>Gets or sets the ItemId field. </summary>
		[DataMember]
		public System.Int32 ItemId { get; set;}
		/// <summary>Gets or sets the ItemSearchTitle field. </summary>
		[DataMember]
		public System.String ItemSearchTitle { get; set;}
		/// <summary>Gets or sets the Name field. </summary>
		[DataMember]
		public System.String Name { get; set;}
		/// <summary>Gets or sets the Order field. </summary>
		[DataMember]
		public Nullable<System.Int32> Order { get; set;}
		/// <summary>Gets or sets the ProfilePath field. </summary>
		[DataMember]
		public System.String ProfilePath { get; set;}
		/// <summary>Gets or sets the ResultNum field. </summary>
		[DataMember]
		public Nullable<System.Int32> ResultNum { get; set;}
		/// <summary>Gets or sets the RowId field. </summary>
		[DataMember]
		public System.Int32 RowId { get; set;}
		/// <summary>Gets or sets the TmdId field. </summary>
		[DataMember]
		public Nullable<System.Int32> TmdId { get; set;}
		#endregion
	}
}
