//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace SqlExpressNovember.EntityClasses
{
	/// <summary>Class which represents the entity 'MovieResult'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class MovieResult : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="MovieResult"/> class.</summary>
		public MovieResult() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the Actors field. </summary>
		[DataMember]
		public System.String Actors { get; set;}
		/// <summary>Gets or sets the AddedOn field. </summary>
		[DataMember]
		public Nullable<System.DateTime> AddedOn { get; set;}
		/// <summary>Gets or sets the ApiUrl field. </summary>
		[DataMember]
		public System.String ApiUrl { get; set;}
		/// <summary>Gets or sets the Awards field. </summary>
		[DataMember]
		public System.String Awards { get; set;}
		/// <summary>Gets or sets the BoxOffice field. </summary>
		[DataMember]
		public System.String BoxOffice { get; set;}
		/// <summary>Gets or sets the ChangedOn field. </summary>
		[DataMember]
		public Nullable<System.DateTime> ChangedOn { get; set;}
		/// <summary>Gets or sets the Country field. </summary>
		[DataMember]
		public System.String Country { get; set;}
		/// <summary>Gets or sets the Director field. </summary>
		[DataMember]
		public System.String Director { get; set;}
		/// <summary>Gets or sets the Dvd field. </summary>
		[DataMember]
		public System.String Dvd { get; set;}
		/// <summary>Gets or sets the Genre field. </summary>
		[DataMember]
		public System.String Genre { get; set;}
		/// <summary>Gets or sets the GenreIds field. </summary>
		[DataMember]
		public System.String GenreIds { get; set;}
		/// <summary>Gets or sets the ImdbId field. </summary>
		[DataMember]
		public System.String ImdbId { get; set;}
		/// <summary>Gets or sets the ImdbRating field. </summary>
		[DataMember]
		public System.String ImdbRating { get; set;}
		/// <summary>Gets or sets the ImdbVotes field. </summary>
		[DataMember]
		public System.String ImdbVotes { get; set;}
		/// <summary>Gets or sets the IsMovie field. </summary>
		[DataMember]
		public Nullable<System.Boolean> IsMovie { get; set;}
		/// <summary>Gets or sets the ItemId field. </summary>
		[DataMember]
		public System.Int32 ItemId { get; set;}
		/// <summary>Gets or sets the ItemSearchTitle field. </summary>
		[DataMember]
		public System.String ItemSearchTitle { get; set;}
		/// <summary>Gets or sets the ItemSearchYear field. </summary>
		[DataMember]
		public Nullable<System.Int32> ItemSearchYear { get; set;}
		/// <summary>Gets or sets the ItemSource field. </summary>
		[DataMember]
		public System.Int32 ItemSource { get; set;}
		/// <summary>Gets or sets the Language field. </summary>
		[DataMember]
		public System.String Language { get; set;}
		/// <summary>Gets or sets the MetaScore field. </summary>
		[DataMember]
		public System.String MetaScore { get; set;}
		/// <summary>Gets or sets the OriginalLanguage field. </summary>
		[DataMember]
		public System.String OriginalLanguage { get; set;}
		/// <summary>Gets or sets the OriginalTitle field. </summary>
		[DataMember]
		public System.String OriginalTitle { get; set;}
		/// <summary>Gets or sets the Overview field. </summary>
		[DataMember]
		public System.String Overview { get; set;}
		/// <summary>Gets or sets the Page field. </summary>
		[DataMember]
		public Nullable<System.Int32> Page { get; set;}
		/// <summary>Gets or sets the Plot field. </summary>
		[DataMember]
		public System.String Plot { get; set;}
		/// <summary>Gets or sets the Popularity field. </summary>
		[DataMember]
		public Nullable<System.Double> Popularity { get; set;}
		/// <summary>Gets or sets the Poster field. </summary>
		[DataMember]
		public System.String Poster { get; set;}
		/// <summary>Gets or sets the PosterPath field. </summary>
		[DataMember]
		public System.String PosterPath { get; set;}
		/// <summary>Gets or sets the Production field. </summary>
		[DataMember]
		public System.String Production { get; set;}
		/// <summary>Gets or sets the Rated field. </summary>
		[DataMember]
		public System.String Rated { get; set;}
		/// <summary>Gets or sets the Released field. </summary>
		[DataMember]
		public System.String Released { get; set;}
		/// <summary>Gets or sets the ReleaseDate field. </summary>
		[DataMember]
		public System.String ReleaseDate { get; set;}
		/// <summary>Gets or sets the Response field. </summary>
		[DataMember]
		public System.String Response { get; set;}
		/// <summary>Gets or sets the ResultCt field. </summary>
		[DataMember]
		public Nullable<System.Int32> ResultCt { get; set;}
		/// <summary>Gets or sets the ResultNum field. </summary>
		[DataMember]
		public Nullable<System.Int32> ResultNum { get; set;}
		/// <summary>Gets or sets the ResultTitle field. </summary>
		[DataMember]
		public System.String ResultTitle { get; set;}
		/// <summary>Gets or sets the ResultYear field. </summary>
		[DataMember]
		public Nullable<System.Int32> ResultYear { get; set;}
		/// <summary>Gets or sets the RowId field. </summary>
		[DataMember]
		public System.Int32 RowId { get; set;}
		/// <summary>Gets or sets the Runtime field. </summary>
		[DataMember]
		public System.String Runtime { get; set;}
		/// <summary>Gets or sets the Tconsensus field. </summary>
		[DataMember]
		public System.String Tconsensus { get; set;}
		/// <summary>Gets or sets the Tfresh field. </summary>
		[DataMember]
		public System.String Tfresh { get; set;}
		/// <summary>Gets or sets the Timage field. </summary>
		[DataMember]
		public System.String Timage { get; set;}
		/// <summary>Gets or sets the Tmeter field. </summary>
		[DataMember]
		public System.String Tmeter { get; set;}
		/// <summary>Gets or sets the TotalPages field. </summary>
		[DataMember]
		public Nullable<System.Int32> TotalPages { get; set;}
		/// <summary>Gets or sets the TotalResults field. </summary>
		[DataMember]
		public Nullable<System.Int32> TotalResults { get; set;}
		/// <summary>Gets or sets the Trating field. </summary>
		[DataMember]
		public System.String Trating { get; set;}
		/// <summary>Gets or sets the Treviews field. </summary>
		[DataMember]
		public System.String Treviews { get; set;}
		/// <summary>Gets or sets the Trotten field. </summary>
		[DataMember]
		public System.String Trotten { get; set;}
		/// <summary>Gets or sets the TuserMeter field. </summary>
		[DataMember]
		public System.String TuserMeter { get; set;}
		/// <summary>Gets or sets the TuserRating field. </summary>
		[DataMember]
		public System.String TuserRating { get; set;}
		/// <summary>Gets or sets the TuserReviews field. </summary>
		[DataMember]
		public System.String TuserReviews { get; set;}
		/// <summary>Gets or sets the Type field. </summary>
		[DataMember]
		public System.String Type { get; set;}
		/// <summary>Gets or sets the Video field. </summary>
		[DataMember]
		public Nullable<System.Boolean> Video { get; set;}
		/// <summary>Gets or sets the VoteAverage field. </summary>
		[DataMember]
		public Nullable<System.Double> VoteAverage { get; set;}
		/// <summary>Gets or sets the VoteCount field. </summary>
		[DataMember]
		public Nullable<System.Int32> VoteCount { get; set;}
		/// <summary>Gets or sets the Website field. </summary>
		[DataMember]
		public System.String Website { get; set;}
		/// <summary>Gets or sets the Writer field. </summary>
		[DataMember]
		public System.String Writer { get; set;}
		#endregion
	}
}
